### ISSUE TITLE
walkAdv_iterateAll memory leak

### ISSUE THREAD

**Issue by Yarkin** [ipld/go-ipld-prime#100]
[profile003.pdf](https://github.com/ipld/go-ipld-prime/files/5415101/profile003.pdf)
leak to 160GB

**Comment by Yarkin** [comment]
![image](https://user-images.githubusercontent.com/1072921/96706280-f6353080-13c8-11eb-91d2-ca397cb5c8bf.png)

**Comment by warpfork** [comment]
Hi!  Thanks for reporting.

However, I think I recognize the application and context this is from, and I'm pretty sure that whatever the root cause is, it's not a bug in this library; go-ipld-prime just shows up in the vicinity.

There's an issue at https://github.com/filecoin-project/go-data-transfer/pull/109 that tracks this... and I've heard the fix shows up in the latest releases of Lotus (which I suspect is what this profile is from:)) too.  Hope that helps :)
