### ISSUE TITLE
Refactor all packages to support 64-bit integers properly

### ISSUE THREAD

**Issue by rvagg** [ipld/go-ipld-prime#124]
Surfaced here https://github.com/ipld/go-codec-dagpb/pull/3 thanks to @marten-seemann including a `GOARCH=386` variant of `go test` on the new DAG-PB codec.

I have a test case in my cross-language compat suite that's testing `Tsize` at 2^53 to push at the JavaScript maximum safe integer boundary. go-ipld-prime is decoding that and `AsInt()` is returning an `int` which truncates down to `-1`.

https://github.com/ipld/go-codec-dagpb/blob/41b03bfa1f20105c0b852dc81e555f5fd16bce12/compat_test.go#L183-L191

Is it feasable, or desirable to convert all of `AsInt()` to an explicit `int64` so we avoid this silly Go arch variability with `int`?

**Comment by mvdan** [comment]
:facepalm: I definitely think that using `int` instead of `int64` here was an oversight. Only supporting 64-bit IPLD integers on 64-bit platforms is rather unfortunate.

As some previous work in this area, Go's reflect package also represents integers as int64, for the same reason: https://golang.org/pkg/reflect/#Value.Int

@warpfork I think we should try to include this in 0.7; thoughts? If it doesn't make the cut, we could always keep it for a future 0.9.

**Comment by mvdan** [comment]
As for whether or not to ignore 32-bit; while it might not matter for the vast majority of IPLD users, I still think 32-bit is here to stay for a while. It would strike me as a bit weird if IPLD did not support 32-bit machines.

**Comment by warpfork** [comment]
Yeah, this should be int64.

I already wrote up a short blurb in the changelog about the need to do this: https://github.com/ipld/go-ipld-prime/blame/5f009262d3ead6c55e6143f8c4f018722ee4916f/CHANGELOG.md#L26-L28

I'll confess, I sort of hate thinking about 32 bit architectures existing, and I'm a little worried that the amount of "ugh, I have to cast to|from int64 here?"-moments our users will have is gonna be, well, "ugh"-filled.  But we're downright spec-noncompliant on 32bit architectures if we don't do this, so there's really not much choice here.

**Comment by mvdan** [comment]
Since the int64 refactor had no issue, I'm repurposing this one.
