### ISSUE TITLE
Support caching of realized IPLD nodes

### ISSUE THREAD

**Issue by willscott** [ipld/go-ipld-prime#128]
If I have a lot of IPLD conformant data in a dag, where i'm pathing through it repeatedly, I might naively create a cache of CID->IPLD.Node lookups so that I don't have to re-parse blocks repeatedly.

However, since nodes hold a reference to all of their children once they've been realized, I can't meaningfully control the size of the cache - each time pathing goes through a node that i keep a reference to all of the subtree that is realized will end up being referenced and will not be cleaned up by GC.

There will ideally be some way to allow children references to fall out of scope over time, or otherwise allow heavily used nodes to stay realized across uses without ending up with unbounded memory growth.

**Comment by warpfork** [comment]
(discussed elsewhere, but for posterity:)

Building a cache like this should be possible.  The cache eviction policy should be something you can decide as part of building that cache.  There is not a direct relationship between an `ipld.Node` and a memory footprint (because it's an interface, and there's more than one implementation), but it's not infinite.

`ipld.Node` values will only point directly to other nodes created from parsing the same block of data.  (And generally, we say a "block" should be in the ballpark of a megabyte or less -- though IPLD libraries don't enforce this, it's a common number we recommend for A) convention, and B) so it's easy to connect up things that do have chunk size limits, such as transports like libp2p.)

Link nodes are just the link themselves, not any larger data.  Links aren't eagerly loaded.  Links don't store a pointer to the referenced data when it's loaded, either (for approximately this reason :) such a cache would need an eviction policy, and it's better to build that from the outside).

ADL nodes may complicate this somewhat, as they may implement internal caching for their substrate data.  We don't yet have any kind of API standard for controlling this.  It might be nice to have such a standard in the future (presumably making it available through some sort of feature-detection interface), but for now I'd say it's too early to try to standardize that, and implementations should experiment freely on this subject (and try to generate experience reports for us on what works, so we can feed that learning into any future standardization efforts).
