### ISSUE TITLE
Getting started with Schemas

### ISSUE THREAD

**Issue by tchardin** [ipld/go-ipld-prime#132]
Hello, I've been playing with the node builders and loving it so far. I'm looking to get a proof of concept up using schemas, it might be too early but is there any chance you could point me to an example how I could get up and running with schemas in go? I've read the authoring specs but I'm not quite sure what the workflow looks like.

Thanks for your help!

**Comment by warpfork** [comment]
Hello, and welcome!

It's a little rough at present.  Be warned you're going to be looking at a very "alpha" experience, with a fair amount of friction.  We haven't made a polished CLI tool for this at all yet :grimacing: so if you want to try it out, you have to write some code against the development APIs rather than actually writing a Schema document in the nice DSL (it's in the aims for this spring, though!).

All that said, a really good executable example is available here: https://github.com/ipld/go-ipld-adl-hamt/blob/25abfe77c0bc35c0f7ccff285a599afd00f0300e/gen.go  You might be able to get something working by riffing off that!

(P.S. If you want a little lower-latency/informal connection than github issues, me and others will also lurk in `#ipld` on IRC on freenode, and/or https://app.element.io/#/room/#ipld:matrix.org (both are bridged together, so, whichever platform you like better works). :grinning: )

**Comment by tchardin** [comment]
Awesome. Thanks for the info!
