### ISSUE TITLE
ability to parse a schema

### ISSUE THREAD

**Issue by mvdan** [ipld/go-ipld-prime#188]
Schemas have been a thing for a while now: https://github.com/ipld/specs/blob/master/schemas/README.md

Unfortunately, we can't actually parse that language yet. Instead, users are expected to write up their schema using the schema package:

```
ts := schema.TypeSystem{}
ts.Init()
ts.Accumulate(schema.SpawnString("String"))
ts.Accumulate(schema.SpawnInt("Int"))
ts.Accumulate(schema.SpawnStruct("Person",
	[]schema.StructField{
		schema.SpawnStructField("Name", "String", false, false),
		schema.SpawnStructField("Age", "Int", true, false),
		schema.SpawnStructField("Friends", "List_String", false, false),
	},
	schema.SpawnStructRepresentationMap(nil),
))
ts.Accumulate(schema.SpawnList("List_String", "String", false))

schemaType := ts.TypeByName("Person")
```

This is unfortunate for many reasons: it's verbose, I have to learn a new API, and I can't just maintain my schema in one place - the schema file.

It would be ideal if I could `go:embed` a schema file, and then use something akin to `schema.Parse(io.Reader) (*schema.TypeSystem, error)`. We could provide convenience wrappers too, like `ts, err := schema.ParseFile(path)`. 

cc @warpfork @willscott

**Comment by rvagg** [comment]
So, we have https://github.com/ipld/go-ipld-schema which does a very manual parse and has its own internal representation for schemas, but it works and is well tested and also in sync with https://github.com/ipld/js-ipld-schema, which IMO does a better job and it has a PEG.js parser definition in there which it uses (so, not so manual as the Go parser). Not saying that we _should_ use go-ipld-schema as a starting point, but it could be that it's easy enough to just wire up the internals so it represents the schema as ipld-prime types. I did started attempting that work a while back but ipld-prime wasn't quite mature enough, and my Go-fu also wasn't quite mature enough! Tests in go-ipld-schema are pretty solid though so they could be helpful.

**Comment by warpfork** [comment]
I think the key step to making this work is just getting a "dmt" form of the schema data available in golang.

Which is "easy".  Just deploy codegen.  Or, now, alternatively, the `bindnode` stuff that @mvdan's also working on.  I think an older issue talked through this: https://github.com/ipld/go-ipld-prime/issues/84 ... and that's still mostly fairly accurate.

Once we've got that "dmt" form ready to use, connecting it to those parsers is... easier than easy.  Just pipe the DAG-JSON through; done.  (Living the dream!)

The real sticking point is connecting the "dmt" form to the golang types we have for `schema.Type*`.  Unfortunately, we run into some nasty package import cycle issues when trying to do that.  We need to figure out how to untangle the `schema` package so that this problem goes away -- we're dead in the water until diffusing that.

**Comment by warpfork** [comment]
I've gathered some more notes on this (especially, focusing on some of the design choices that get steered into extra tricky waters by import cycle issues): https://www.notion.so/protocollabs/2021-07-go-schema-usability-next-steps-b5606836314241649f6a0a2e1d1906ec

(I think I've made that link world-published; someone yell at me if not.  Perhaps I'm a monster for using Notion for this, but I kinda wanted to try life with color coding :))

That doc tries to overview some potential approaches and their tradeoffs.  It also tries to recover some learning I got from jousting at this unsuccessfully in the past.  (It may be wise to take those bits with a grain of salt.  It's possible I missed some simplifications somewhere that'll be glaringly obvious to fresh eyes.  It's possible we should just flat out drop some things I previously considered constraints.  And I also suspect using bindnode instead of codegen might reduce a lot of complexities drastically, meaning we might be in a better place now than the last time I tried to work on this.  Lots of reasons to be optimistic.)

---

The most useful part I'll replicate here for ease of reference: it's breaking down which phases the data passes through:

Four phases of data:

1. The Schema DSL (which is what humans generally want to write and display in their docs).
2. The Schema DMT, serialized.  (Generally, as JSON.  We have DSL→JSON tools to do this.)
3. The Schema DMT, loaded into go, as `ipld.Node`.  (Note!  Still a DAG!)
4. The `schema.*` types, which are very similar to phase#3, except offer helper methods someone actually wants to use, and also carry the implication that they've been checked for coherency.

We have tools for phase#1→phase#2.

We have some generated code that can do phase#2→phase#3.  (But might want to revisit if we want to do this or bindnode, now.)

**We need phase#3→phase#4.**

(And we currently have some temp constructors that jump directly to phase#4.  (These are what mvdan showed in the initial post.)  And indeed, we really don't like these; they don't help us connect the lower numbers up to phase#4, which means it's not helping us move in the directions we want to move in.)
