### ISSUE TITLE
add an API to declare the standard "prelude" types to a schema type system

### ISSUE THREAD

**Issue by mvdan** [ipld/go-ipld-prime#208]
See https://github.com/ipld/go-ipld-prime/pull/207#discussion_r675033222.

**Comment by mvdan** [comment]
Bonus points if this also makes initializing a typesystem easier. Right now it's:

```
ts := schema.TypeSystem{}
ts.Init()
// accumulate all basic types
```

Would be nice if it was instead just something like:

```
ts := schema.StandardTypeSystem() // already includes basic types
```

**Comment by mvdan** [comment]
The new `func MustTypeSystem(types ...Type) *TypeSystem` in master seems close to this; imagine if I could do:

    ts := schema.MustTypeSystem(schema.Prelude...)

I'd slightly prefer just `schema.StandardTypeSystem()` though, since it would be clearer it should never error/panic, and it's also more descriptive without the `schema.` package repetition.

**Comment by mvdan** [comment]
FYI @warpfork ^ since you did https://github.com/ipld/go-ipld-prime/pull/232

**Comment by warpfork** [comment]
Yeah, we should have something for this.

I didn't form strong opinions on how exactly it should be written (because I still sort of wish we could get away from these golang constructors at all, but, here we are for a while yet, it seems).

A list of prelude types that one can unroll into the varargs for MustTypeSystem would seem good, I guess, if we can get away with something that light.

Or, I've also now a couple of times had the wish for a constructor method for TypeSystem that takes both an existing TypeSystem and a list of new types and just adds them together to form a new one.  (This mostly has come up in tests, and I'm not sure the desire is very correct, on second thought.  Just a thought.)

**Comment by mvdan** [comment]
`dmt.Compile` now spawns the full prelude:

https://github.com/ipld/go-ipld-prime/blob/ac5b5fd4b203318fd5b0fbef13401be9c84e991f/schema/dmt/compile.go#L15-L33

And I think we're in agreement that the vast majority of users should use schemas by using `ipld.LoadSchema` and the DSL rather than manually spawning and accumulating types.

For that reason, I think we can close this issue. Note that the prelude doesn't include `Null` right now; that's blocked on support for unit typekinds, so I've raised https://github.com/ipld/go-ipld-prime/issues/336 as a reminder.
