### ISSUE TITLE
selector for limiting recursion over a field

### ISSUE THREAD

**Issue by willscott** [ipld/go-ipld-prime#237]
In cases of a dag in a git-like dag
<img width="425" alt="image" src="https://user-images.githubusercontent.com/428199/131820915-72f05b88-7a57-47a7-a8bf-12720f430b45.png">

It would be useful to have a selector that's able to get the chain (the nodes labeled 'vn', 'vn-1', etc), including the CIDs of the roots pointed to in each object, but not pulling in the full data dags linked in each.

This can be mostly achieved today with a combination of the field-recursion and stop-at, but it seems like that might skip including the CID of the link to the root as well.

**Comment by warpfork** [comment]
This might seem like kind of a low-brow question, but... Can't you just obtain the desired effect by listing the fields you *do* want to recurse over, and not the ones that you... don't?

I ask because -- while I'm also not going to say the proposal in https://github.com/ipld/go-ipld-prime/pull/240 is nonviable -- I think you'll get better performance out of saying what you want, rather than asking the selector to look at everything and then using further logic to toss things back out of consideration again.  In other words, even if we had both these features -- I'd probably council someone to use the simpler more direct one unless they're really, really sure they can't for some reason.

**Comment by warpfork** [comment]
In the git example, the recursion you describe wanting keeps following "parent" fields, and just never askes to follow a "tree" field, and... that's it, right?

I think this is pretty common in most protocols I've seen -- there's some fields that we want to walk, that point to more data (often, data of the same "type", not that we explicitly know about that in selectors), and there's some we just don't ever want to walk (because it's going to point to different "types" of stuff, e.g. file trees in git instead of commits).

So if we have an example where that logic doesn't hold, it'd be kinda fun to look at it in a bit more detail as a case study.  I'd probably want to attach those case study notes to docs somewhere for "why would you want to use this feature".

**Comment by rvagg** [comment]
closing this for now but this can be picked up by anyone who feels this is really important and useful and wants to do an implementation because current options are unsatisfactory for various reasons (it'll also probably be important to clarify _why_ as per the comments above)
