### ISSUE TITLE
Common selectors are in the wrong place

### ISSUE THREAD

**Issue by willscott** [ipld/go-ipld-prime#249]
https://github.com/ipld/go-ipld-prime/blob/master/traversal/selector/parse/selector_parse.go#L66-L94

Why are they in the `parse` package? They should be in `traversal` or `traversal/selector`, and not there.

**Comment by warpfork** [comment]
Yeah.  https://github.com/ipld/go-ipld-prime/issues/236 would be how I want to solve this.

(Things are currently in the parse package because I wanted to make an executed example of how to write a Selector in JSON, but was unwilling to make _all_ use of selectors depend on the JSON parser package.  A reorg of packages to get the engine stuff in a less central place would make it possible to both have and eat the cake.)

**Comment by warpfork** [comment]
I think I'll close this because #236 has the more actionable plan in it already, but it remains good evidence that there's a user need for these packages to be less confusingly organized, so thanks for opening it.
