### ISSUE TITLE
node/bindnode: Prototype slightly too needy for pointers?

### ISSUE THREAD

**Issue by warpfork** [ipld/go-ipld-prime#349]
The `bindnode.Prototype` function will panic with `"bindnode: ptrType must be a pointer" if given non-pointers.

This does what it says, certainly, so there's no bug here, per se.  But I wonder if it needs to be quite so strict in this requirement of pointers.

It feels awkward that the following does not work, for example: `bindnode.Prototype([]Foobar{}, tinfo)` will produce that panic.  Instead, the closest acceptable code is `bindnode.Prototype((*[]Foobar)(nil), tinfo)`.  This also then means that getting content made from that prototype back out as golang native types later will look like `bindnode.Unwrap(nb.Build()).(*[]Foobar)` -- the pointer feels a bit unnatural here, too.

This isn't an important issue, because it's certainly easy to work around.  It just feels a bit strange in the example above.

**Comment by mvdan** [comment]
The reason to use pointers internally is because interfaces must always contain pointers. Not using a pointer is worse for the user, because it hides that detail from them, and _forces_  the allocation to happen for the pointer - for example, when calling `bindnode.Wrap` with a `T` rather than `*T`. With a `*T`, you can choose how or whether to allocate the pointer.

So I think we're in agreement that we should support pointers. What about supporting non-pointers as well?

I could see us going either way on that. I lean towards not supporting them because:

* It's easier to reason about the API if it always works with pointers everywhere. If we support both, `Unwrap` would have to ask the user to be careful to type-assert according to their pointer usage at the time they called `Wrap` or `Prototype`.
* We entirely remove the pitfall that is unintentionally causing allocations with interfaces.
* Not using pointers only has a relatively minor win in terms of verbosity, and it's almost entirely contained in the call to `Prototype`, which most users will call at most once in their code.

**Comment by mvdan** [comment]
All of this said, I have also wanted to type `Foo([]T, bar)` before - that is, passing a type to a function without also having to construct an empty value, be it nil or a zero-length slice. We could consider using generics for a proper type parameter, like `Prototype[*[]FooBar](tinfo)`, but that sounds overkill and doesn't actually help with the syntax that much.

**Comment by mvdan** [comment]
I'm going to close this for now, because pointers work and they're consistent, and I don't see strong reasons why we should change the status quo.

I will say one more thing in favor of the consistency of pointers - you can use `(*T)(nil)` for _any_ `T`, even for basic types like `int`. When passing non-pointer types, that gets less consistent, as you can't do e.g. `int{}`.
