### ISSUE TITLE
node/bindnode: support passing a NodePrototype to Wrap

### ISSUE THREAD

**Issue by mvdan** [ipld/go-ipld-prime#351]
I keep writing and seeing code like:

    node := bindnode.Wrap(msg, ipldbind.Prototype.Message.Type())

There's nothing wrong with that, but notice how we it's kind of verbose. I wonder if we should also support passing the prototype directly:

    node := bindnode.Wrap(msg, ipldbind.Prototype.Message)

and then `Wrap` would call the `Type` method itself.

We could implement this today by replacing `schemaType schema.Type` with `typeOrProto interface{}`, as a form of union between `schema.Type` and `schema.TypedPrototype`. However, note that we'd lose type safety; one could pass `123` or `"foo"` to such a function and it would only fail at run-time.

We could wait for generics, but unfortunately we can't write the union `interface{ schema.Type | schema.TypedPrototype }` because the spec says:

> Implementation restriction: A union with more than one term cannot contain interface types with non-empty [method sets](https://tip.golang.org/ref/spec#Method_sets)

They might lift this restriction in the future, but we probably shouldn't wait for that.

Overall, I think we should do nothing here; just logging it as a thought before we reject the idea. cc @warpfork @rvagg @willscott

**Comment by rvagg** [comment]
ultimately I think for most people using this (I could be underestimating the audience here but I include myself too) it'll just be magic incantations with a significant amount of complexity behind it that's not worth trying to understand in detail. You just type out that form and adjust it to meet your needs and move on to the things you actually care about. Shorter magic incantations are usually best, but making them _more_ magic may not be advisable because you might end up relying on the user to actually understand what's really going on.

**Comment by warpfork** [comment]
Agree, would reject :)

The strongest argument for me is that `interface{}` in method signatures fails to be self-documenting.  If I see that as a new user splelunking the API docs, I have no idea where to stride next.

**Comment by mvdan** [comment]
Alright, we're in agreement :)
