### ISSUE TITLE
node/bindnode: allow nilable types instead of a pointer for optional/nullable schemas

### ISSUE THREAD

**Issue by mvdan** [ipld/go-ipld-prime#378]
For example, right now, to bind an IPLD `struct { Foo optional Any }`, one must use a pointer for the field type, like `struct { Foo *datamodel.Node }`.

However, in this case and some others, the Go type `datamodel.Node` already has a `nil` state to signal "absent", so we could reuse that instead of adding our own via a pointer. Not only is that type easier for the user to read and write, but it's also less prone to bugs, because a pointer to an interface has two nil states: nil pointer, and non-nil pointer to a nil interface.

This would also apply to IPLD schema's `nullable`, which similarly requires a pointer now.

This would have helped with https://github.com/ipld/go-ipld-prime/pull/371, and also with the new https://github.com/ipld/go-ipld-prime/issues/377.

What to do with `optional nullable` fields remains a bit of a TODO, because right now those use two chained pointers, which is a bit weird. We might want to rethink that with generics at some point, to end up with a wrapper like `OptionalNullable` that keeps two boolean fields, akin to https://github.com/ipld/go-ipld-prime/issues/340.

**Comment by rvagg** [comment]
Thinking aloud: I wonder if `optional nullable` needs an additional specifier to dictate the default value, like `implicit`: `Foo optional nullable Any (implicit "null")`, or maybe something dedicated like `(defaultnull)` - such that bindnode could use this as a hint so that when serializing a `nil` field it'll know to put in a Null rather than leave it out. You'd still not get the ability to serialize an absent, but maybe that won't matter in most cases if you can control it via schema and allow deserialization to _just work_?

**Comment by BigLep** [comment]
@mvdan : are you going to be able to finish landing this before leaving?

**Comment by mvdan** [comment]
@BigLep I have a work-in-progress patch that I intend to send by the end of the week; it might not land this week, but since this is open source, I'm not too worried about it leaking into next week.
