### ISSUE TITLE
Bindnode: optional + nullable & cbor-gen

### ISSUE THREAD

**Issue by hannahhoward** [ipld/go-ipld-prime#396]
As we look to replace cbor-gen go-structs with bind node, there is an interesting and subtle incompatibility between cbor-gen & bindnode.

The current cbor-gen code treats pointer in structs with map-encoding as follows:
- on serialization, it writes a null (analagous to schema type `nullable`)
- on deserialization, it accepts a null value  (analagous to schema type `nullable`), BUT it also accepts the field being simply absent (analagous to schema type `optional`)

This makes the field essentially both optional and nullable, but the current bindnode support requires this be a ** (i.e pointer to pointer), which then presents a significant conversion cost on the go struct, plus double pointers are terrible to work with.

The context this came up in is a non-go language version of go-data-transfer was taking advantage of cbor-gen's support for optional fields in deserialization, and found the messages they generated were no longer compatible when we switched to a data transfer message build from bindnode + IPLD schema.

**Comment by mvdan** [comment]
See https://github.com/ipld/go-ipld-prime/issues/352.

**Comment by rvagg** [comment]
@hannahhoward do you have the specific example/struct they were hitting with this?

**Comment by hannahhoward** [comment]
Actually came from https://github.com/tchardin -- the javascript data-transfer library for example was leaving the Response field off of the top level message when sending a request -- https://github.com/myelnet/js-dcdn/blob/4250c419ec18e542200345624ab3b178d208c635/packages/data-transfer/src/data-transfer.ts#L416

But with our new schema -- https://github.com/filecoin-project/go-data-transfer/blob/master/message/message1_1prime/schema.ipldsch#L33 -- that field is expected to be present with null value

**Comment by rvagg** [comment]
I'm going to close this one out, for a couple of reasons:

1. We're much closer to bindnode compat now with the type converters.
2. cbor-gen is relaxed about parsing when it comes to optional||nullable, so if bindnode does the strict thing then cbor-gen will be fine with it.
3. _If_ we have a case where this is important, let's deal with it then rather than leave this dangling. Bending the optional||nullable distinction to meet cbor-gen is not really what we want to be doing, and if we did it it'd be an opt-in thing for bindnode users. We have a way to pass options now so it may not be hard to do but it certainly wouldn't be a standard behaviour thing.

So, this can be reopened in the future, or if someone shows up with a good reason why this needs to happen then we can deal with it then.
