### ISSUE TITLE
'Interpret As' should really specify a Schema, not an ADL

### ISSUE THREAD

**Issue by softwareplumber** [ipld/go-ipld-prime#441]
The many 'representation' options for Structs, Maps, and Unions in a schema mean that the actual path through the DAG may vary substantially between different representations. Also there is really no easy way to even define a selector for some representations (for example, the string pair representation of a map). It would be incredibly useful to specify a schema (perhaps by CID) in a selector so that Structs, Maps, and Unions can be traversed in the same way irrespective of their representation. Since an ADL can be signaled in a schema, it could be argued that 'Interpret As' should really flag a schema rather than directly flagging an ADL. Backwards compatibility could be achieved by having the system interpret any string which does not match a known ADL as a schema CID.

**Comment by softwareplumber** [comment]
Hmm, that kind of presupposes that we are executing some code to transform the DAG before traversal. Which is different to using a Schema to direct DAG traversal. Even if both might achieve the same, the former has potentially unbounded cost whereas the latter is mostly a transformation of the path plus some extra filters.

**Comment by justincjohnson** [comment]
I'm still getting my bearings in IPLD land, so forgive me if I'm off here.

I believe this issue is about the desire to be able to specify a selector using knowledge of a schema instead of being tied to the exact representation of the data in the DAG (e.g. ability to navigate into a named struct field instead of using knowledge of how that struct is represented in the DAG).   If that is true, I'm interested in this as well, whatever the means to get there.

**Comment by expede** [comment]
I could be misinterpreting @willscott's comment above, but @softwareplumber perhaps some context if the comment alludes to an autocodec. There's been some side discussion about pulling taking schemas and ADLs out of IPLD, and forcing semantic information up into application space. One theory for how this would be achieved is by attaching the CID of a Wasm blob to the DAG, which exposes the interpretation. Implementations could also special case these and not run them with Wasm; it's just a canonical identifier for that behaviour. Adding more schemas this way also means that new ones become available without needing to load them ahead of time.

**Comment by softwareplumber** [comment]
@expede I read @willscott's comment a little more narrowly than that - specifying transformations of the DAG via a CID of some WASM as a natural way to make ADLs portable. Bumping the whole schema/transformation thing to a different layer is an orthogonal discussion. Schemas have a utility - for example in validating a selector before any attempt is made to process it - which makes it a mistake to consider a schema as just a simpler way to direct DAG traversal than an ADL.

**Comment by aschmahmann** [comment]
I'd recommend taking a look at @warpfork's exploration report on lenses https://github.com/ipld/ipld/pull/190 and well as other exploration repo rts discussing signaling and the ipld.io website's comments on ADLs and signaling namely (copy-pasting here):

> naming and signalling are separate problems with separate solutions. (The solutions interact, but don't confuse the problems.)

---

What I hear in this issue is basically an issue that `InterpretAs` is the most convenient signaling mechanism available at the moment and there's a desire to have a signaling mechanism for schemas. Sure, I could potentially see how you could use Schema -> ADL mapping here (even though you'll probably run into issues specifying an ADL transform on a root node) but it sounds like the complaint is more "why is my use case not supported" than "why is that other person's use case supported".

> Backwards compatibility could be achieved by having the system interpret any string which does not match a known ADL as a schema CID.

I guess, but also there's plenty of room to go around here. Selectors are described with schemas and we should be able to just add more union cases (either within `InterpretAs` or elsewhere) without needing to play games like this.

> I think the eventual intention is for interpretAs to flag a CID for a wasm interpretation, which can then perform the work of either a schema or an ADL.

I'm called out the signaling != naming thing above to try and help clear this up. When you keep signaling == naming you end up with arguments like:
- Alice wants to name the `InterpretAs` `as` clause using a CID for a selector because selectors are simple
- But Bob wants to name the `InterpretAs` `as` clause using a CID for a WASM ADL because it gives more freedom and work today
- But Carol wants to name the `InterpretAs` `as` clause using a CID for a WASM Lenses because they give even more freedom

But .... Alice, Bob and Carol are basically all arguing that the `InterpretAs` `as` clause is a useful signaling location and are competing with each other based on what the name should be. Next thing you know someone will say "hey, actually let's have the `InterpretAs` `as` clause point at a CID that has a schema for a union of Links to Schemas, ADLs, or Lenses" at which point it probably makes sense to take a step back and ask if you could just make room for all their signals at the selector schema layer instead.

Leaning into the Selector Schema here allows us to also do things like support Selectors with schemas included in them by being explicit rather than some implicit mechanism with identity multihashes. e.g. instead of `Schema &Any` having something like:

```
type SchemaData union {
  | External &Any
  | Internal map
} representation kinded
```

**Comment by softwareplumber** [comment]
Heartily agree with all of what you say above, @aschmahmann - expanding the Selector schema to allow for both embedded schemas and schema references would be ideal.

**Comment by rvagg** [comment]
While this is a useful addition to the ongoing discussion about schema (and adl) signalling and selecting, I'm not really seeing actionable items here.

If someone wants to take this further into action, a PR here and/or to https://github.com/ipld/ipld would probably be a good next step, and then we can look at specific proposals. IMO there's still a few missing pieces that get us to loading external schemas and/or ADL. Maybe a PR or concrete proposal for what that external-loading wiring would look like in go-ipld-prime might be interesting.

I might close this issue unless there are objections—although closing it isn't intended to shut down the conversation, it can be continued.
