### ISSUE TITLE
could not choose an encoder: no encoder registered for multicodec code 113

### ISSUE THREAD

**Issue by Rock-liyi** [ipld/go-ipld-prime#447]
I have tried  using the code  provided  by [the documentation ](https://github.com/ipld/go-ipld-prime/blob/master/linking/linkingExamples_test.go  ) for using    ExampleLinkSystem_Store() function ,
but it  give a warning  what  "could not choose an encoder: no encoder registered for multicodec code 113"
so, what should i do ?

![image](https://user-images.githubusercontent.com/35133768/177006131-e6b4ac33-a067-4ab5-a1c0-cf6a20f3d1fb.png)

**Comment by rvagg** [comment]
You're probably missing the import for dag-cbor (which is 0x71), from the top of that example:

```go
	_ "github.com/ipld/go-ipld-prime/codec/dagcbor"
```

it's a blank import because it's not used directly, but it does need to be _registered_ as a codec for it to work transparently in the LinkSystem: https://github.com/ipld/go-ipld-prime/blob/adf99676901e35d42bba09c67a236ee0c87675f0/codec/dagcbor/multicodec.go#L16-L19

**Comment by Rock-liyi** [comment]
> You're probably missing the import for dag-cbor (which is 0x71), from the top of that example:
> 
> ```go
> 	_ "github.com/ipld/go-ipld-prime/codec/dagcbor"
> ```
> 
> it's a blank import because it's not used directly, but it does need to be _registered_ as a codec for it to work transparently in the LinkSystem:
> 
> https://github.com/ipld/go-ipld-prime/blob/adf99676901e35d42bba09c67a236ee0c87675f0/codec/dagcbor/multicodec.go#L16-L19

Ok, it works, thanks!
