### ISSUE TITLE
dag-json vs. json: is json trully json?

### ISSUE THREAD

**Issue by hacdias** [ipld/go-ipld-prime#470]
Hi!

We're considering supporting actual `json` and `cbor` data formats in Kubo ([ref](https://github.com/ipfs/kubo/pull/9335)). As I was testing if JSON worked properly, I run into the following:

```
~ ❯ ipfs dag put --input-codec json --store-codec json
ipfs: Reading from /dev/stdin; send Ctrl-d to stop.
{ 10: "hello" }
Error: unexpected int token while expecting map key
```

After looking at the code, it seems that the codec `json` actually uses the codec `dag-json` for decoding (and encoding), which means that `json` doesn't support many of the features of real JSON.

https://github.com/ipld/go-ipld-prime/blob/7548eb883bda4712355797547a0628a0ad1c00cb/codec/json/multicodec.go#L24-L33

Is this a bug, or not? If not, why? If yes, are there any plans for fixing this?

**Comment by rvagg** [comment]
It's not so much that json uses dag-json, it's that they both share the underlying engine which happens to have a mode whereby it can interpret `{"/":"..."}` as links and `{"/":{"bytes":"..."}}` as bytes.

It's not going to yield the same flexibility as "proper" JSON because the IPLD data model has some other constraints - and you're running into one of them here - map keys can only be strings, which arguably should also be true in JSON but because it's related to JavaScript we get to throw in integers too.

What we _could_ do is allow parsing of `{10:"hello"}` but it'd have to be turned in to `{"10":"hello"}` internally.
