### ISSUE TITLE
rename ReprKind to just Kind

### ISSUE THREAD

**Issue by mvdan** [ipld/go-ipld-prime#94]
This is everywhere, so the shorter name will make writing code significantly nicer. And an ipld-prime kind is still not an ambiguous concept.

This would break practically all users, but the fix is easy via search-and-replace.

/cc @warpfork

**Comment by warpfork** [comment]
I'm in favor of this.

There's the potential for confusion between _type_ kinds and _representation (aka Data Model) kinds_.

To review:
- Representation/DM kinds are: `null|bool|int|float|string|bytes|link|map|list`.
- Type kinds are: `unit|bool|int|float|string|bytes|link|map|list|struct|union|enum` -- a slightly bigger set.

However, I think the package structure and other parts of the way we refer to these things is probably clear enough:

- `ipld.Kind` would be the representation/DM kinds
- `schema.Kind` contains the type kinds
- `n.(ipld.Node).Kind()` returns an `ipld.Kind`
- `n.(schema.TypedNode).Kind()` **is still stuck returning an `ipld.Kind`**, because it overlaps with the general Node interface
- `n.(schema.TypedNode).Type().Kind()` returns a `schema.Kind`.

**Comment by mvdan** [comment]
I agree; the named types being in different packages should be enough of a nudge that they're distinct.

**Comment by rvagg** [comment]
+1 to this renaming, I was reaching for "kind" the other day and felt very wrong for what I was doing to be reaching for the "ReprKind", I just wanted the plain kind of the data model object I was interrogating, not the underlying representation kind.

**Comment by warpfork** [comment]
Ooh yeah double good point.

**Comment by warpfork** [comment]
I've thought about this a bit more and have some notes:

- goal: be able to use X and "typekind" in a prose sentence unambiguously.
- how about `ipld.Kind` and `schema.TypeKind`?  (Rename both at once.)
	- clear in most conversations
	- people will have to say "typekind" when they mean "typekind" and this seems well and good
	- examples of talking about it in a prose sentence:
		- "all nodes have a kind"
		- "a schema node has a typekind"
		- "a schema node has a kind (like all nodes)"
		- "a schema node has a representation, which also a has a kind"
		- "a typekind implies a specific kind (usually; kinded unions and the any typekind are an exception)"
		- a tad unfortunate in prose: "a schema node's typekind is different than it's kind", but maybe about as good as it gets
		- relatively decent in prose: "a schema node's kind can be different than its representation kind"
	- `schema.TypedNode` interface has `.Type().Kind()` (returns `schema.TypeKind`) and `.Kind()` (returns `ipld.Kind` -- has to, because method is already in the `ipld.Node` interface) and `.Representation().Kind()` (returns `ipld.Kind`)... and this seems well and good, and seems to align well with the prose

So all in all, this is almost the same as what I proposed in the [october comment](https://github.com/ipld/go-ipld-prime/issues/94#issuecomment-709257450), but nixing `schema.Kind` in favor of `schema.TypeKind`, because I think that's going to line up better with the prose way we talk about this stuff in specs and docs and when crossing over to other languages.

**Comment by mvdan** [comment]
SGTM. I wonder if SchemaKind would be a bit nicer than TypeKind, unless "type kind" is already a well-established concept in IPLD specs. It just feels like TypeKind is slightly more ambiguous, because conceptually a data model kind is very similar to a basic type.

**Comment by warpfork** [comment]
I gave that one a think overnight, but I think I still prefer TypeKind to SchemaKind.  Schemas contain more info than only types, and the keyword in the DSL (and the type name prefix in the DMT) is "type"... so there's good precedent for "type" to be prefixed to "kind" in this way.

The conceptual proximity and potential confusion between types and kinds and etc is still a worry, but it's also kinda the baseline.  I think we just have to pick vocab and use it relentlessly consistently.

**Comment by mvdan** [comment]
Fair enough. My only ask is that "typekind" become a well used term in IPLD specs or other implementations, and not just a Go quirk :)

**Comment by warpfork** [comment]
I gave the github "+1" reaction to that, but the actual intensity I want there there is somewhere between :100:  and +1000000.

**Comment by ribasushi** [comment]
+1 on
> `ipld.Kind` and `schema.TypeKind` (Rename both at once.)

**Comment by rvagg** [comment]
sounds reasonable to me, although this is one of those things where opinions may change once in use so we'll see!
